#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\Commands\AlarmCommand;
use App\Repositories\Verisure\InstallationRepository;
use App\Repositories\Verisure\JobStatusRepository;
use App\Repositories\Verisure\LoginRepository;
use GuzzleHttp\Client;
use Symfony\Component\Console\Application;
use Symfony\Component\DomCrawler\Crawler;
use Symfony\Component\Dotenv\Dotenv;

$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

$application = new Application();

$client = new Client();
$crawler = new Crawler();

$installationRepository = new InstallationRepository($client, $crawler);
$jobStatusRepository = new JobStatusRepository($client, $crawler);
$loginRepository = new LoginRepository($client, $crawler);

$application->add(new AlarmCommand($installationRepository, $jobStatusRepository, $loginRepository));

$application->run();